#! /bin/bash

set -e

filename=$(date "+%Y%m%d%H%M%S")

#shellcheck disable=SC2120
zet() {
    header="#${filename} ${1:-"Default title"}"

     echo "$header" > "$filename.md"
     code "$filename.md"
}

